apiVersion: v1
kind: ConfigMap
metadata:
  name: custody-super-admin-api-config
data:
  APP_NAME: custody_super_admin
  NODE_ENV: PROD
  PORT: "3000"
  #HOST: "*.custody.roxcustody.io"
  APP_URL: "https://api-admin.roxcustody.io"
  CORPORATE_DASHBOARD_URL: "https://*.roxcustody.io"


  #DATABASE_WRITE_HOST: "aurora-cluster-rox-api.cluster-cf02y0oys1cq.eu-north-1.rds.amazonaws.com"
  #DATABASE_READ_HOST: "aurora-cluster-rox-api.cluster-cf02y0oys1cq.eu-north-1.rds.amazonaws.com"
  DATABASE_NAME: "rox_api_database"
  DATABASE_PORT: "3306"
  DATABASE_USER: "admin"
  DATABASE_TENANT_PREFIX_NAME: "prod"


  REDIS_PORT_NUMBER: "15976"
  REDIS_DB_NUMBER: "0"

  MAIL_FROM: no-reply@dafa.sa
  MAIL_HOST: smtp.gmail.com
  MAIL_PORT: "587"
  MAIL_USER: no-reply@dafa.sa
  SENDGRID_EMAIL: noreply@roxcustody.io
  RABBITMQ_TOPIC_EXCHANGE: custodyExchangeTopic

  CUSTODY_SOLUTION_SERVICE_NAME: roxcustody_super_admin
  CUSTODY_SUPER_ADMIN_SERVICE_NAME: roxcustody_super_admin
  RABBITMQ_CUSTODY_QUEUE_NAME: roxcustody_corporate_prod
  RABBITMQ_SUPERADMIN_QUEUE_NAME: roxcustody_superadmin_prod
  RABBITMQ_CUSTODY_SOLUTION_QUEUE_NAME: "roxcustody_corporate_prod"
  
  AWS_ENDPOINT: "https://s3.amazonaws.com"
  AWS_DOMAIN: "s3.amazonaws.com"
  BUCKETREGION : "eu-north-1"
  BUCKETNAME: "custody-prod"
  AWS_DIRECTORY: "/public"

  # JWT CONFIGURATIONS
  FORGET_PASSWORD_JWT_EXPIRES_IN: "1d"
  JWT_EXPIRES_IN: "30d"
  JWT_SECRET: "Cg!psbg7PRes^q!E66N"
  FORGET_PASSWORD_JWT_SECRET: "adhgdfvsghdjkfhsjkfg"