apiVersion: v1
kind: ConfigMap
metadata:
  name: custody-private-server-config
data:
  # APPLICATION CONFIGURATIONS
  NODE_ENV: "PROD"

  DATABASE_HOST: "mysql-instance-private-server.cf02y0oys1cq.eu-north-1.rds.amazonaws.com"
  #DATABASE_WRITE_HOST: "aurora-cluster-private-server.cluster-cf02y0oys1cq.eu-north-1.rds.amazonaws.com"
  #DATABASE_READ_HOST: "aurora-cluster-private-server.cluster-ro-cf02y0oys1cq.eu-north-1.rds.amazonaws.com"
  DATABASE_NAME: "private_server_database"
  DATABASE_PORT: "3306"
  DATABASE_USER: "admin"

  # RABBITMQ CONFIGURATIONS
  RABBITMQ_URL: "amqps://vnnojfgt:Oz7wQuW_4R9-jqDc8jLcJuWU4byLbuY9@loyal-black-scorpion.rmq4.cloudamqp.com/vnnojfgt"
  RABBITMQ_CUSTODY_PRIVATE_SERVER_QUEUE_NAME: "rox_custody_private_server"

  TRON_API_KEY: "6f398b6c-d47d-4d65-b846-cf83a73cf6a6"
