apiVersion: v1
kind: ConfigMap
metadata:
  name: custody-keys-bridge-config
data:
  NODE_ENV: "PROD"
  PORT: "80"

  # RABBITMQ CONFIGURATIONS
  RABBITMQ_URL: "amqps://vnnojfgt:Oz7wQuW_4R9-jqDc8jLcJuWU4byLbuY9@loyal-black-scorpion.rmq4.cloudamqp.com/vnnojfgt"
  RABBITMQ_CUSTODY_QUEUE_NAME: "roxcustody_corporate_prod"
  RABBITMQ_CUSTODY_PRIVATE_SERVER_QUEUE_NAME: "rox_custody_private_server"
  RABBITMQ_CUSTODY_BRIDGE_QUEUE_NAME: "roxcustody_keys_bridge"

  DATABASE_HOST: "mysql-instance-key-bridge.cf02y0oys1cq.eu-north-1.rds.amazonaws.com"
  #DATABASE_WRITE_HOST: "aurora-cluster-key-bridge.cluster-cf02y0oys1cq.eu-north-1.rds.amazonaws.com"
  #DATABASE_READ_HOST: "aurora-cluster-key-bridge.cluster-ro-cf02y0oys1cq.eu-north-1.rds.amazonaws.com"
  DATABASE_NAME: "key_bridge_database"
  DATABASE_PORT: "3306"
  DATABASE_USER: "admin"

  SENDGRID_API_KEY: "CHANGE_ME"
  SENDGRID_EMAIL: "noreply@roxcustody.io"
