apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: custody-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-north-1:780202038201:certificate/7c30a2c8-ff6d-48dc-bee9-717a2a373703
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=3600



spec:
  rules:

    - host: kibana.roxcustody.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quickstart-kb-http
                port:
                  number: 5601

    - host: api-admin.roxcustody.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: custody-super-admin-api-service
                port:
                  number: 80

    - host: superadmin.roxcustody.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: custody-super-admin-dashboard-service
                port:
                  number: 80

    - host: "*.api.roxcustody.com"  # Uses wildcard cert for subdomains
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: custody-solution-api-service
                port:
                  number: 80

    - host: "*.roxcustody.com"  # Uses wildcard cert for subdomains
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: custody-solution-corporate-dashboard-service
                port:
                  number: 80
